apiVersion: v1
kind: Service
metadata:
  name: sungava-it-club-service
  namespace: sungava-it-club
spec:
  type: LoadBalancer
  selector:
    app: sungava-it-club
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000




